const TAU=Math.PI*2,rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class ParticleSystem{
  constructor(){this.enabled=true;this.items=[];this.nextId=1;this.frame=0;this.profile={slices:2,max:850,draw:650,spawn:1,glow:1};this.stats={emitted:0,dropped:0,drawn:0}}
  setEnabled(v){this.enabled=!!v;if(!this.enabled)this.clear()}
  clear(){this.items.length=0;this.stats.drawn=0}
  configure(p){this.profile={slices:Math.max(1,p.particleSlices||2),max:Math.max(0,p.maxParticles||500),draw:Math.max(0,p.drawParticles||350),spawn:clamp(p.particleSpawn??1,0,1),glow:clamp(p.glow??1,.2,1)};if(this.items.length>this.profile.max)this.items.splice(0,this.items.length-this.profile.max)}
  add(s,important=false){
    if(!this.enabled)return null;if(!important&&Math.random()>this.profile.spawn)return null;
    if(this.items.length>=this.profile.max){if(!important){this.stats.dropped++;return null}const i=this.items.findIndex(p=>!p.important);i>=0?this.items.splice(i,1):this.items.shift()}
    const now=performance.now(),p={id:this.nextId++,important,x:s.x||0,y:s.y||0,z:s.z||0,vx:s.vx||0,vy:s.vy||0,vz:s.vz||0,gravity:s.gravity??-18,drag:s.drag??.92,life:s.life??.55,born:now,updated:now,size:s.size??4,endSize:s.endSize??.6,color:s.color||'#8ff7e2',alpha:s.alpha??1,shape:s.shape||'dot',rotation:s.rotation||0,spin:s.spin||0,length:s.length||12,width:s.width||2,dead:false};this.items.push(p);this.stats.emitted++;return p
  }
  burst(kind,x,y,o={}){if(!this.enabled)return;const count=Math.max(1,Math.round((o.count||12)*this.profile.spawn)),color=o.color||'#8ff7e2';for(let i=0;i<count;i++){const a=o.angle==null?Math.random()*TAU:o.angle+rand(-(o.spread||.8),o.spread||.8),speed=rand(o.speedMin||55,o.speedMax||190);this.add({x:x+rand(-4,4),y:y+rand(-4,4),z:o.z||rand(6,24),vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,vz:rand(o.vzMin??15,o.vzMax??85),gravity:o.gravity??-110,drag:o.drag??.92,life:rand(o.lifeMin||.24,o.lifeMax||.62),size:rand(o.sizeMin||2,o.sizeMax||6),endSize:o.endSize??.4,color:Array.isArray(color)?color[i%color.length]:color,shape:kind==='spark'?'streak':kind==='shard'?'diamond':'dot',length:rand(8,24),width:rand(1,3),rotation:a,spin:rand(-6,6),alpha:o.alpha??1},!!(o.important&&i<6))}}
  aura(x,y,color='#77f4db'){if(!this.enabled||Math.random()>.45*this.profile.spawn)return;const a=Math.random()*TAU,r=rand(20,38);this.add({x:x+Math.cos(a)*r,y:y+Math.sin(a)*r,z:rand(0,18),vx:-Math.cos(a)*rand(4,15),vy:-Math.sin(a)*rand(4,15),vz:rand(16,42),gravity:5,drag:.98,life:rand(.45,.9),size:rand(2,5),endSize:.3,color,alpha:.72})}
  dashTrail(x,y,d){if(!this.enabled)return;const sx=-d.y,sy=d.x;for(let i=0;i<Math.max(2,Math.round(5*this.profile.spawn));i++){const l=rand(-24,24);this.add({x:x-d.x*rand(10,55)+sx*l,y:y-d.y*rand(10,55)+sy*l,z:rand(0,14),vx:-d.x*rand(35,90)+sx*rand(-18,18),vy:-d.y*rand(35,90)+sy*rand(-18,18),vz:rand(8,28),gravity:-20,drag:.9,life:rand(.2,.48),size:rand(5,12),endSize:1.5,color:i%2?'#7fe9ff':'#d8ffff',alpha:.65,shape:'smoke'})}}
  update(dt,now=performance.now()){
    this.frame++;if(!this.enabled||!this.items.length)return;const slices=this.profile.slices,bucket=this.frame%slices;
    for(let i=bucket;i<this.items.length;i+=slices){const p=this.items[i];if(!p||p.dead)continue;const age=(now-p.born)/1000;if(age>=p.life){p.dead=true;continue}const e=Math.min(.085,Math.max(0,(now-p.updated)/1000));if(!e)continue;const drag=Math.pow(p.drag,e*60);p.vx*=drag;p.vy*=drag;p.vz+=p.gravity*e;p.x+=p.vx*e;p.y+=p.vy*e;p.z+=p.vz*e;if(p.z<0){p.z=0;p.vz*=-.22;p.vx*=.72;p.vy*=.72}p.rotation+=p.spin*e;p.updated=now}
    if(this.frame%24===0||this.items.length>this.profile.max*1.05){this.items=this.items.filter(p=>!p.dead&&(now-p.born)/1000<p.life);if(this.items.length>this.profile.max)this.items.splice(0,this.items.length-this.profile.max)}
  }
  draw(ctx,project,now=performance.now(),view={width:innerWidth,height:innerHeight}){
    this.stats.drawn=0;if(!this.enabled||!this.items.length||this.profile.draw<=0)return;const stride=Math.max(1,Math.ceil(this.items.length/this.profile.draw)),offset=this.frame%stride;ctx.save();ctx.globalCompositeOperation='lighter';
    for(let i=offset;i<this.items.length;i+=stride){const p=this.items[i];if(!p||p.dead)continue;const age=(now-p.born)/1000;if(age<0||age>=p.life)continue;const lag=Math.min(.05,Math.max(0,(now-p.updated)/1000)),pos=project(p.x+p.vx*lag,p.y+p.vy*lag,Math.max(0,p.z+p.vz*lag));if(pos.x<-40||pos.x>view.width+40||pos.y<-40||pos.y>view.height+40)continue;const t=age/p.life,fade=(1-t)*p.alpha,size=p.size+(p.endSize-p.size)*t;ctx.globalAlpha=fade;ctx.fillStyle=p.color;ctx.strokeStyle=p.color;
      if(p.shape==='streak'){const a=Math.atan2(p.vy,p.vx),len=p.length*(1-t*.55);ctx.lineWidth=Math.max(.7,p.width*(1-t));ctx.beginPath();ctx.moveTo(pos.x,pos.y);ctx.lineTo(pos.x-Math.cos(a)*len,pos.y-Math.sin(a)*len*.62);ctx.stroke()}
      else if(p.shape==='diamond'){ctx.save();ctx.translate(pos.x,pos.y);ctx.rotate(p.rotation);ctx.beginPath();ctx.moveTo(0,-size);ctx.lineTo(size*.65,0);ctx.lineTo(0,size);ctx.lineTo(-size*.65,0);ctx.closePath();ctx.fill();ctx.restore()}
      else{if(p.shape==='smoke')ctx.globalAlpha=fade*.45;else{ctx.shadowBlur=7*this.profile.glow;ctx.shadowColor=p.color}ctx.beginPath();ctx.arc(pos.x,pos.y,Math.max(.5,size),0,TAU);ctx.fill();ctx.shadowBlur=0}
      if(++this.stats.drawn>=this.profile.draw)break
    }ctx.restore()
  }
}
export class VisualEffects{
  constructor(){this.items=[];this.texts=[];this.shake=0}
  arc(s){this.items.push({type:'arc',age:0,life:s.life||.32,...s})}ring(s){this.items.push({type:'ring',age:0,life:s.life||.4,...s})}damageText(x,y,value,heavy=false){this.texts.push({x,y,value,heavy,age:0,life:heavy?.85:.65})}hitShake(a){this.shake=Math.max(this.shake,a)}
  update(dt){for(const i of this.items)i.age+=dt;for(const t of this.texts){t.age+=dt;t.y-=dt*(t.heavy?46:34)}this.items=this.items.filter(i=>i.age<i.life);this.texts=this.texts.filter(t=>t.age<t.life);this.shake*=Math.pow(.02,dt);if(this.shake<.05)this.shake=0}
  drawWorld(ctx,project,particles){for(const i of this.items){const t=i.age/i.life,alpha=(1-t)*(i.alpha??1),p=project(i.x,i.y,i.z||10);ctx.save();ctx.globalCompositeOperation=particles?'lighter':'source-over';ctx.globalAlpha=alpha;ctx.translate(p.x,p.y);ctx.scale(1,.62);ctx.strokeStyle=i.color||'#b7fff1';if(i.type==='arc'){ctx.lineWidth=(i.width||16)*(1-t*.72);ctx.lineCap='round';if(particles){ctx.shadowColor=i.color||'#8ef3e2';ctx.shadowBlur=18}ctx.beginPath();ctx.arc(0,0,(i.radius||110)*(.82+t*.24),i.start,i.end,i.ccw||false);ctx.stroke();if(particles){ctx.globalAlpha=alpha*.75;ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(1.5,(i.width||16)*.18);ctx.beginPath();ctx.arc(0,0,(i.radius||110)*(.84+t*.22),i.start,i.end,i.ccw||false);ctx.stroke()}}else{ctx.lineWidth=Math.max(1,(i.width||8)*(1-t));if(particles){ctx.shadowBlur=16;ctx.shadowColor=i.color||'#72eaff'}ctx.beginPath();ctx.arc(0,0,(i.radius||70)*(.35+t*.9),0,TAU);ctx.stroke()}ctx.restore()}}
  drawText(ctx,project){ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';for(const t of this.texts){const k=t.age/t.life,p=project(t.x,t.y,48);ctx.globalAlpha=1-k;ctx.font=`${t.heavy?900:800} ${t.heavy?24:17}px system-ui`;ctx.lineWidth=4;ctx.strokeStyle='rgba(0,0,0,.72)';ctx.strokeText(String(t.value),p.x,p.y);ctx.fillStyle=t.heavy?'#ffe88a':'#f1fbff';ctx.fillText(String(t.value),p.x,p.y)}ctx.restore()}
}
