const TAU=Math.PI*2;
export const DIRECTIONS=[{x:1,y:0,name:'东'},{x:.7071,y:.7071,name:'东南'},{x:0,y:1,name:'南'},{x:-.7071,y:.7071,name:'西南'},{x:-1,y:0,name:'西'},{x:-.7071,y:-.7071,name:'西北'},{x:0,y:-1,name:'北'},{x:.7071,y:-.7071,name:'东北'}];
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function normalize(x,y){const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}}
export function quantizeDirection(x,y,fallback=DIRECTIONS[2]){if(Math.hypot(x,y)<.12)return fallback;let a=Math.atan2(y,x);if(a<0)a+=TAU;return DIRECTIONS[Math.round(a/(TAU/8))%8]}
export class SpatialHash{
  constructor(cellSize=96){this.cellSize=cellSize;this.cells=new Map()}
  key(x,y){return`${Math.floor(x/this.cellSize)},${Math.floor(y/this.cellSize)}`}
  rebuild(items){this.cells.clear();for(const item of items){if(item.dead)continue;const key=this.key(item.x,item.y);let cell=this.cells.get(key);if(!cell)this.cells.set(key,cell=[]);cell.push(item)}}
  nearby(x,y,r){const out=[],minX=Math.floor((x-r)/this.cellSize),maxX=Math.floor((x+r)/this.cellSize),minY=Math.floor((y-r)/this.cellSize),maxY=Math.floor((y+r)/this.cellSize);for(let cy=minY;cy<=maxY;cy++)for(let cx=minX;cx<=maxX;cx++){const c=this.cells.get(`${cx},${cy}`);if(c)out.push(...c)}return out}
}
export class Hero{
  constructor(){this.reset()}
  reset(){this.x=0;this.y=0;this.dir=DIRECTIONS[2];this.speed=238;this.hp=100;this.maxHp=100;this.invulnerable=0;this.hitFlash=0;this.attack=null;this.dash=null;this.dead=false;this.respawn=0;this.combo=0;this.comboWindow=0;this.walkPhase=0}
  update(dt,m){this.invulnerable=Math.max(0,this.invulnerable-dt);this.hitFlash=Math.max(0,this.hitFlash-dt);this.comboWindow=Math.max(0,this.comboWindow-dt);if(this.dead){this.respawn-=dt;return}if(this.dash){this.x+=this.dash.x*this.dash.speed*dt;this.y+=this.dash.y*this.dash.speed*dt;this.dash.time-=dt;if(this.dash.time<=0)this.dash=null;this.walkPhase+=dt*19;return}const mag=Math.min(1,Math.hypot(m.x,m.y));if(mag>.05){const n=normalize(m.x,m.y);this.dir=quantizeDirection(n.x,n.y,this.dir);const slow=this.attack&&this.attack.kind!=='attack'?.48:this.attack?.72:1;this.x+=n.x*this.speed*mag*slow*dt;this.y+=n.y*this.speed*mag*slow*dt;this.walkPhase+=dt*10*mag}}
  damage(v){if(this.dead||this.invulnerable>0)return false;this.hp=Math.max(0,this.hp-v);this.invulnerable=.55;this.hitFlash=.18;if(this.hp<=0){this.dead=true;this.respawn=2.2;this.attack=null;this.dash=null}return true}
}
export class Enemy{
  constructor(id,x,y,tier=0){this.id=id;this.x=x;this.y=y;this.tier=tier;this.radius=tier?25:20;this.maxHp=tier?110:62;this.hp=this.maxHp;this.speed=tier?63:80+Math.random()*18;this.vx=0;this.vy=0;this.dirX=0;this.dirY=1;this.attackCooldown=Math.random()*.7;this.hitFlash=0;this.knockX=0;this.knockY=0;this.lastAi=performance.now();this.dead=false;this.deathAge=0;this.walkPhase=Math.random()*TAU}
  applyDamage(v,kx,ky){if(this.dead)return false;this.hp-=v;this.hitFlash=.16;this.knockX+=kx;this.knockY+=ky;if(this.hp<=0){this.dead=true;this.deathAge=0;this.vx=this.vy=0;return true}return false}
  updateMotion(dt){this.hitFlash=Math.max(0,this.hitFlash-dt);this.attackCooldown-=dt;if(this.dead){this.deathAge+=dt;return}this.x+=(this.vx+this.knockX)*dt;this.y+=(this.vy+this.knockY)*dt;const d=Math.pow(.02,dt);this.knockX*=d;this.knockY*=d;this.walkPhase+=dt*(4+this.speed*.025);if(Math.hypot(this.vx,this.vy)>2){const n=normalize(this.vx,this.vy);this.dirX=n.x;this.dirY=n.y}}
}
function shadow(ctx,x,y,rx,ry,a=.3){ctx.save();ctx.globalAlpha=a;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,TAU);ctx.fill();ctx.restore()}
function swordPose(h){let angle=-.35,reach=35,lift=0;if(h.attack){const t=clamp(h.attack.age/h.attack.duration,0,1),swing=h.attack.kind==='spin'?t*TAU*1.5:h.attack.kind==='slash'?-2.3+t*4.2:-1.7+t*3.2;angle=swing+(h.attack.combo===2?.35:h.attack.combo===3?-.25:0);reach=h.attack.kind==='slash'?48:h.attack.kind==='spin'?42:39;lift=Math.sin(t*Math.PI)*5}return{angle,reach,lift}}
export function drawHero(ctx,h,project,now,fx=true){const p=project(h.x,h.y,0),view=Math.atan2(h.dir.y*.62,h.dir.x),moving=h.dash||Math.abs(Math.sin(h.walkPhase))>.05,bob=moving?Math.sin(h.walkPhase*2)*1.6:Math.sin(now*.003)*.7,fade=h.dead?clamp(1-h.respawn/2.2,0,1):1;ctx.save();ctx.globalAlpha=1-fade*.82;shadow(ctx,p.x,p.y+4,27,11,h.dead?.12:.34);ctx.restore();if(h.dead)return;ctx.save();ctx.translate(p.x,p.y-18+bob);ctx.rotate(view);if(h.hitFlash>0){ctx.globalCompositeOperation='lighter';ctx.shadowBlur=18;ctx.shadowColor='#ff8d95'}const step=Math.sin(h.walkPhase)*5;ctx.strokeStyle='#172431';ctx.lineWidth=8;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-8,19);ctx.lineTo(-8-step*.32,31);ctx.moveTo(8,19);ctx.lineTo(8+step*.32,31);ctx.stroke();ctx.fillStyle='#26394a';ctx.beginPath();ctx.ellipse(-9-step*.32,32,8,4,0,0,TAU);ctx.ellipse(9+step*.32,32,8,4,0,0,TAU);ctx.fill();ctx.fillStyle=h.hitFlash>0?'#ffe4e6':'#27485a';ctx.strokeStyle='#87c8d5';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-18,-4);ctx.lineTo(-14,20);ctx.quadraticCurveTo(0,28,15,20);ctx.lineTo(18,-4);ctx.quadraticCurveTo(0,-15,-18,-4);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#122d3c';ctx.fillRect(-4,-7,8,30);ctx.fillStyle='#f0c46c';ctx.fillRect(-17,12,34,4);ctx.fillStyle='#496d7c';ctx.strokeStyle='#9cd1d9';ctx.beginPath();ctx.moveTo(-20,-7);ctx.lineTo(-10,-18);ctx.lineTo(-3,-8);ctx.lineTo(-12,2);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(20,-7);ctx.lineTo(10,-18);ctx.lineTo(3,-8);ctx.lineTo(12,2);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#d6a77f';ctx.beginPath();ctx.arc(0,-23,11,0,TAU);ctx.fill();ctx.fillStyle='#243b4c';ctx.beginPath();ctx.arc(0,-26,12,Math.PI,TAU);ctx.lineTo(10,-22);ctx.lineTo(-10,-22);ctx.closePath();ctx.fill();ctx.fillStyle='#b9f4ff';ctx.fillRect(4,-25,3,2);const s=swordPose(h);ctx.save();ctx.translate(12,-4);ctx.rotate(s.angle);ctx.strokeStyle='#d7a85f';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-5,1);ctx.lineTo(7,1);ctx.stroke();ctx.strokeStyle='#6d4930';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(0,7);ctx.lineTo(0,17);ctx.stroke();const g=ctx.createLinearGradient(0,-s.reach,0,0);g.addColorStop(0,'#fff');g.addColorStop(.35,'#bffff4');g.addColorStop(1,'#5ab9cb');ctx.strokeStyle=g;ctx.lineWidth=7;ctx.lineCap='round';if(fx){ctx.shadowColor='#6fffe2';ctx.shadowBlur=13}ctx.beginPath();ctx.moveTo(0,-2);ctx.lineTo(0,-s.reach-s.lift);ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#fff';ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(-1,-4);ctx.lineTo(-1,-s.reach);ctx.stroke();ctx.restore();if(fx){ctx.globalCompositeOperation='lighter';ctx.globalAlpha=.18+Math.sin(now*.006)*.04;ctx.strokeStyle='#72f5d6';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,30,34,12,0,0,TAU);ctx.stroke()}ctx.restore()}
export function drawEnemy(ctx,e,project){const p=project(e.x,e.y,0);if(e.dead&&e.deathAge>.55)return;const t=e.dead?clamp(e.deathAge/.55,0,1):0;shadow(ctx,p.x,p.y+3,e.radius*.9*(1-t*.6),e.radius*.36,.26*(1-t));ctx.save();ctx.translate(p.x,p.y-13+Math.sin(e.walkPhase*2)*1.2);ctx.scale(1,1-t*.85);ctx.globalAlpha=1-t;ctx.rotate(Math.atan2(e.dirY*.62,e.dirX));if(e.hitFlash>0){ctx.globalCompositeOperation='lighter';ctx.shadowBlur=12;ctx.shadowColor='#fff'}const big=e.tier>0,step=Math.sin(e.walkPhase)*4;ctx.strokeStyle='#1b2a22';ctx.lineWidth=big?8:6;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-7,13);ctx.lineTo(-8-step*.25,24);ctx.moveTo(7,13);ctx.lineTo(8+step*.25,24);ctx.stroke();ctx.fillStyle=e.hitFlash>0?'#fff4df':big?'#6f7745':'#52724c';ctx.strokeStyle='#263a2a';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,4,big?19:15,big?21:17,0,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle=big?'#7c8550':'#668558';ctx.beginPath();ctx.arc(0,-13,big?14:11,0,TAU);ctx.fill();ctx.beginPath();ctx.moveTo(-8,-19);ctx.lineTo(-18,-24);ctx.lineTo(-10,-10);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(8,-19);ctx.lineTo(18,-24);ctx.lineTo(10,-10);ctx.closePath();ctx.fill();ctx.fillStyle='#ffb867';ctx.fillRect(4,-15,3,2);ctx.fillStyle='#1e1713';ctx.fillRect(-2,-7,8,2);if(big){ctx.strokeStyle='#b8a86f';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-18,-1);ctx.lineTo(-30,10);ctx.stroke()}ctx.restore();if(!e.dead&&e.hp<e.maxHp){const w=big?48:38,r=clamp(e.hp/e.maxHp,0,1);ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(p.x-w/2,p.y-57,w,5);ctx.fillStyle=big?'#f1b14d':'#e65c64';ctx.fillRect(p.x-w/2+1,p.y-56,(w-2)*r,3)}}
