import {BOSS_TYPES,DAYS,HEROES,ISO_Y,PASSIVES,QUALITY_PROFILES,TAU,WEAPONS,dayById,weightedPick} from './config.js';
import {Enemy,Hazard,Pickup,Player,Projectile,SpatialHash,clamp,drawEnemy,drawHazard,drawPickup,drawPlayer,drawProjectile,normalize} from './entities.js';
import {ParticleSystem,VisualEffects} from './effects.js';
import {dataText,t} from './i18n.js';
const rand=(a,b)=>a+Math.random()*(b-a),chance=p=>Math.random()<p,dist2=(a,b,c,d)=>(a-c)**2+(b-d)**2;
class Pool{constructor(make){this.make=make;this.free=[]}get(){return this.free.pop()||this.make()}put(v){v.active=false;if(this.free.length<700)this.free.push(v)}}
class Ground{draw(ctx,w,h,camera,map){const palettes={frost:['#0a2730','#173b42'],rift:['#102735','#1b4050'],grove:['#122b28','#29483a'],mine:['#141f2c','#2b3d4e'],lake:['#0a2931','#174650'],ruins:['#18272b','#3c4942'],throne:['#111824','#292d45']},[a,b]=palettes[map]||palettes.frost,g=ctx.createRadialGradient(w/2,h/2,20,w/2,h/2,Math.max(w,h));g.addColorStop(0,b);g.addColorStop(1,a);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(130,210,220,.09)';ctx.lineWidth=1;const ox=(((-camera.x+w/2)%96)+96)%96,oy=(((-camera.y*ISO_Y+h/2)%61)+61)%61;for(let y=oy-61;y<h+61;y+=61)for(let x=ox-96;x<w+96;x+=96){const o=Math.round(y/61)%2?48:0;ctx.beginPath();ctx.moveTo(x+o,y-30);ctx.lineTo(x+o+48,y);ctx.lineTo(x+o,y+30);ctx.lineTo(x+o-48,y);ctx.closePath();ctx.stroke()}const v=ctx.createRadialGradient(w/2,h/2,Math.min(w,h)*.25,w/2,h/2,Math.max(w,h)*.75);v.addColorStop(0,'transparent');v.addColorStop(1,'rgba(0,4,8,.46)');ctx.fillStyle=v;ctx.fillRect(0,0,w,h)}}
export class Game{
 constructor({canvas,store,audio,callbacks={}}){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});this.store=store;this.audio=audio;this.cb=callbacks;this.player=new Player;this.player.reset(HEROES.bladeguard,{});this.enemyPool=new Pool(()=>new Enemy);this.projectilePool=new Pool(()=>new Projectile);this.pickupPool=new Pool(()=>new Pickup);this.hazardPool=new Pool(()=>new Hazard);this.enemies=[];this.projectiles=[];this.pickups=[];this.hazards=[];this.grid=new SpatialHash(104);this.nearby=[];this.particles=new ParticleSystem(()=>this.store.data.settings);this.visuals=new VisualEffects(()=>this.store.data.settings,a=>this.vibrate(a));this.ground=new Ground;this.camera={x:0,y:0};this.width=innerWidth;this.height=innerHeight;this.dpr=1;this.running=false;this.paused=false;this.awaitingChoice=false;this.day=DAYS[0];this.mode='campaign';this.hero=HEROES.bladeguard;this.elapsed=0;this.remaining=360;this.spawnTimer=0;this.boss=null;this.bossSpawned=false;this.frame=0;this.last=performance.now();this.acc=0;this.frameEma=16.7;this.lastRender=0;this.hudTimer=0;this.pendingLevels=0;this.selectedChoices=[];this.manualHeld=false;this.magnetForce=0;this.runStats={};this.resize=this.resize.bind(this);addEventListener('resize',this.resize,{passive:true});this.resize();requestAnimationFrame(x=>this.loop(x))}
 get settings(){return this.store.data.settings}
 resize(){this.width=innerWidth;this.height=innerHeight;const p=QUALITY_PROFILES[this.settings.particleQuality]||QUALITY_PROFILES.medium;this.dpr=Math.min(devicePixelRatio||1,this.settings.batterySaver?1.15:p.dpr);this.canvas.width=Math.max(1,Math.round(this.width*this.dpr));this.canvas.height=Math.max(1,Math.round(this.height*this.dpr));this.canvas.style.width=`${this.width}px`;this.canvas.style.height=`${this.height}px`}
 project(x,y,z=0){return{x:x-this.camera.x+this.width/2+(this.shakeX||0),y:(y-this.camera.y)*ISO_Y+this.height/2-z+(this.shakeY||0)}}
 clear(){for(const e of this.enemies)this.enemyPool.put(e);for(const v of this.projectiles)this.projectilePool.put(v);for(const v of this.pickups)this.pickupPool.put(v);for(const v of this.hazards)this.hazardPool.put(v);this.enemies.length=this.projectiles.length=this.pickups.length=this.hazards.length=0;this.particles.clear();this.visuals.items.length=this.visuals.texts.length=0}
 dailyDay(){const base=DAYS[(new Date().getDate()-1)%Math.min(7,this.store.data.unlockedDay)];return{...base,id:100,sourceDayId:base.id,bossId:base.id,title:'每日试炼',duration:420,enemyCap:Math.round(base.enemyCap*1.08),rewardCoins:420,rewardShards:2}}
 startRun({mode='campaign',dayId=1}={}){this.clear();this.mode=mode;this.day=mode==='daily'?this.dailyDay():mode==='endless'?{...DAYS[6],id:999,sourceDayId:7,bossId:7,title:'无尽冰原',duration:Infinity,enemyCap:145,rewardCoins:0,rewardShards:0}:dayById(dayId);this.hero=HEROES[this.store.data.selectedHero]||HEROES.bladeguard;this.player.reset(this.hero,this.store.data.meta);this.camera.x=this.camera.y=0;this.elapsed=0;this.remaining=this.day.duration;this.spawnTimer=0;this.boss=null;this.bossSpawned=mode==='endless';this.running=true;this.paused=false;this.awaitingChoice=false;this.pendingLevels=0;this.manualHeld=false;this.magnetForce=0;this.runStats={kills:0,levels:0,runCoins:0,bosses:0,survival:0,damageTaken:0};for(let i=0;i<12;i++)this.spawnEnemy(i%7?'grunt':'brute',360+Math.random()*260);this.audio.ensure();this.cb.onRunStart?.({day:this.day,mode,hero:this.hero});this.cb.onWeapons?.(this.player);this.updateHud(true)}
 rank(){return Math.min(7,Math.max(1,this.day.sourceDayId||this.day.bossId||this.day.id||1))}
 enemyCap(){const q=QUALITY_PROFILES[this.settings.particleQuality]||QUALITY_PROFILES.medium;return Math.max(28,Math.round(this.day.enemyCap*q.enemyScale*(this.settings.batterySaver?.78:1)))}
 live(){let n=0;for(const e of this.enemies)if(e.active&&!e.dead)n++;return n}
 difficulty(){return(1+(this.rank()-1)*.16)*(1+this.elapsed/330*(.42+(this.rank()-1)*.025))*(this.mode==='endless'?1+Math.floor(this.elapsed/120)*.2:1)}
 spawnEnemy(type=null,radius=null,elite=null){if(this.live()>=this.enemyCap())return null;const a=Math.random()*TAU,r=radius||Math.max(this.width,this.height/ISO_Y)*.62+rand(220,400),id=type||weightedPick(this.day.weights||DAYS[0].weights),e=this.enemyPool.get().reset(id,this.player.x+Math.cos(a)*r,this.player.y+Math.sin(a)*r/ISO_Y,this.difficulty(),elite??chance(.015+this.rank()*.004));this.enemies.push(e);return e}
 spawnBoss(){if(this.bossSpawned||this.mode==='endless')return;this.bossSpawned=true;const id=Math.min(7,this.day.bossId||this.day.id),def=BOSS_TYPES[id],a=Math.random()*TAU,b=this.enemyPool.get().reset('boss',this.player.x+Math.cos(a)*620,this.player.y+Math.sin(a)*620/ISO_Y,1+this.rank()*.08,false,def);b.bossId=id;this.enemies.push(b);this.boss=b;this.audio.boss();this.cb.onToast?.(t('dynamic.bossArrived',{value:dataText('bosses',id,'name',def.name)}))}
 setPaused(v){if(!this.running||this.awaitingChoice)return;this.paused=!!v;this.cb.onPause?.(this.paused)}
 quitRun(){if(this.running)this.finish(false,true)}
 setManualHeld(v){this.manualHeld=!!v}
 useActive(a){if(!this.running||this.paused||this.awaitingChoice||this.player.dead)return false;if(a==='manual'){this.manualHeld=true;return this.manualSlash()}if(a==='dash'){const ok=this.player.dash();if(ok){this.audio.skill('dash');this.particles.burst(this.player.x,this.player.y,{count:12,colors:['#72e9ff','#fff'],shapes:['smoke','streak']})}return ok}if(a==='ultimate')return this.ultimate();if(a==='magnet'){const ok=this.player.magnetPulse();if(ok){this.magnetForce=1.4;this.audio.skill('magnet');this.visuals.ring({x:this.player.x,y:this.player.y,radius:260,width:10,color:'#9d8cff'})}return ok}return false}
 manualSlash(){const p=this.player;if(p.cooldowns.manual>0)return false;p.manualCombo=p.manualWindow>0?p.manualCombo%3+1:1;p.manualWindow=.58;p.cooldowns.manual=(.42-p.manualCombo*.025)*p.cooldownMultiplier(true);const r=(112+p.manualCombo*8)*p.areaMultiplier(),dmg=(20+p.manualCombo*7)*p.damageMultiplier(),hits=this.damageCone(p.x,p.y,p.facing.x,p.facing.y,r,p.manualCombo===3?1.7:1.3,dmg,p.manualCombo===3?250:145,p.manualCombo===3);const a=Math.atan2(p.facing.y,p.facing.x);this.visuals.arc({x:p.x,y:p.y,radius:r*.82,width:13+p.manualCombo*2,start:a-1.1,end:a+1.1,life:.23,color:p.manualCombo===3?'#ffe394':'#8ffff0'});this.audio.swing(p.manualCombo);if(hits)this.audio.hit(p.manualCombo===3);return true}
 ultimate(){const p=this.player;if(!p.spendUltimate())return false;let hits=0;for(const e of this.enemies){if(e.dead)continue;const dx=e.x-p.x,dy=e.y-p.y,d=Math.hypot(dx,dy)||1;if(d>360+e.radius)continue;this.damageEnemy(e,220*p.damageMultiplier(),dx/d*380,dy/d*380,true,.5);hits++}for(let i=0;i<4;i++)this.visuals.ring({x:p.x,y:p.y,radius:90+i*70,width:17-i*2,life:.65,color:i%2?'#9c83ff':'#72edff'});this.particles.burst(p.x,p.y,{count:54,colors:['#fff1a1','#70eeff','#a180ff'],important:true,speedMax:420});this.visuals.hit(14);this.audio.skill('ultimate');this.cb.onToast?.(t('dynamic.ultimateHits',{value:hits}));return true}
 damageEnemy(e,d,kx=0,ky=0,heavy=false,slow=0){const r=e.applyDamage(d,kx,ky,slow);if(!r.damage)return;this.visuals.text(e.x,e.y,r.damage,heavy);this.particles.burst(e.x,e.y,{count:heavy?18:8,colors:['#fff','#7ff1dc','#ffd36c'],important:heavy});if(r.died)this.killEnemy(e)}
 damageCone(x,y,dx,dy,r,cone,dmg,knock,heavy=false){let hits=0;for(const e of this.enemies){if(e.dead)continue;const ex=e.x-x,ey=e.y-y,d=Math.hypot(ex,ey)||1;if(d>r+e.radius||Math.acos(clamp(ex/d*dx+ey/d*dy,-1,1))>cone/2)continue;this.damageEnemy(e,dmg,ex/d*knock,ey/d*knock,heavy,heavy?.18:0);hits++}if(hits)this.visuals.hit(heavy?8:4);return hits}
 damageCircle(x,y,r,dmg,knock=120,heavy=false,slow=0){let hits=0;for(const e of this.enemies){if(e.dead)continue;const dx=e.x-x,dy=e.y-y,d=Math.hypot(dx,dy)||1;if(d>r+e.radius)continue;this.damageEnemy(e,dmg,dx/d*knock,dy/d*knock,heavy,slow);hits++}return hits}
 damagePlayer(v){const a=this.player.damage(v);if(!a)return;this.runStats.damageTaken+=a;this.audio.hurt();this.visuals.hit(7);if(this.player.dead)this.finish(false,false)}
 killEnemy(e){this.player.kills++;this.runStats.kills++;this.player.gainEnergy(e.boss?35:e.elite?8:2.2);this.pickups.push(this.pickupPool.get().reset('xp',e.x,e.y,e.xpValue));if(e.coinValue&&chance(.32))this.pickups.push(this.pickupPool.get().reset('coin',e.x+rand(-8,8),e.y+rand(-8,8),e.coinValue));if(chance(.009))this.pickups.push(this.pickupPool.get().reset('food',e.x,e.y,1));if(e.boss){this.runStats.bosses++;this.pickups.push(this.pickupPool.get().reset('shard',e.x,e.y,Math.max(2,Math.ceil(this.rank()/2))))}}
 nearest(){let best=null,bd=Infinity;for(const e of this.enemies){if(e.dead)continue;const d=dist2(this.player.x,this.player.y,e.x,e.y);if(d<bd){bd=d;best=e}}return best}
 updateWeapons(dt){for(const w of this.player.weapons.values()){w.cooldown-=dt;w.phase+=dt;if(w.id==='orbit'){if(w.cooldown<=0){w.cooldown=.22;this.damageCircle(this.player.x,this.player.y,78+w.level*10,(7+w.level*3)*this.player.damageMultiplier(),60,false,.08)}continue}if(w.cooldown>0)continue;const p=this.player,m=p.cooldownMultiplier(p.moving),target=this.nearest();if(!target){w.cooldown=.25;continue}const d=normalize(target.x-p.x,target.y-p.y);if(w.id==='blade'){w.cooldown=(1.1-w.level*.08)*m;this.damageCone(p.x,p.y,d.x,d.y,(125+w.level*9)*p.areaMultiplier(),1.35,(25+w.level*8)*p.damageMultiplier(),150,w.level>=5);const a=Math.atan2(d.y,d.x);this.visuals.arc({x:p.x,y:p.y,radius:105+w.level*7,width:14,start:a-.75,end:a+.75,color:'#8fffe7'})}else if(w.id==='lightning'){w.cooldown=(1.65-w.level*.1)*m;let cur=target,used=new Set;for(let i=0;i<2+Math.floor(w.level/2);i++){if(!cur)break;used.add(cur);this.damageEnemy(cur,(20+w.level*7)*p.damageMultiplier(),0,0,w.level>=5,.08);const from=cur;cur=this.enemies.filter(e=>!e.dead&&!used.has(e)).sort((a,b)=>dist2(from.x,from.y,a.x,a.y)-dist2(from.x,from.y,b.x,b.y))[0];if(cur)this.visuals.beam({x:from.x,y:from.y,x2:cur.x,y2:cur.y,width:5,color:'#78dcff'})}}else if(w.id==='chakram'){w.cooldown=(1.5-w.level*.08)*m;this.projectiles.push(this.projectilePool.get().reset({x:p.x,y:p.y,z:18,vx:d.x*(330+w.level*18),vy:d.y*(330+w.level*18),radius:11,damage:(18+w.level*7)*p.damageMultiplier(),life:1.5,pierce:2+Math.floor(w.level/2),color:'#8ef0ff',type:'chakram',owner:p}))}else if(w.id==='mine'){w.cooldown=(2.2-w.level*.12)*m;this.hazards.push(this.hazardPool.get().reset({x:p.x,y:p.y,radius:(72+w.level*10)*p.areaMultiplier(),warmup:.7,life:1.1,damage:(38+w.level*14)*p.damageMultiplier(),color:'#72e7d0',type:'mine'}))}else if(w.id==='nova'){w.cooldown=(2.4-w.level*.13)*m;const r=(120+w.level*18)*p.areaMultiplier();this.damageCircle(p.x,p.y,r,(22+w.level*8)*p.damageMultiplier(),170,w.level>=5,.22);this.visuals.ring({x:p.x,y:p.y,radius:r,width:14,color:'#a8fff0'})}}}
 updateEnemies(dt){this.grid.rebuild(this.enemies);const p=this.player,skip=this.frame%(this.settings.batterySaver?4:3);for(let i=0;i<this.enemies.length;i++){const e=this.enemies[i];if(!e.active)continue;if(!e.dead&&i%(this.settings.batterySaver?4:3)===skip){const d=normalize(p.x-e.x,p.y-e.y),dist=Math.hypot(p.x-e.x,p.y-e.y);e.vx=d.x*e.speed;e.vy=d.y*e.speed;if(e.ranged&&dist<260){e.vx*=-.35;e.vy*=-.35;if(e.attackCooldown<=0){e.attackCooldown=e.attackRate;this.projectiles.push(this.projectilePool.get().reset({friendly:false,x:e.x,y:e.y,z:18,vx:d.x*220,vy:d.y*220,radius:7,damage:e.damage,life:3,color:'#c98aff',type:'bolt'}))}}}e.updateMotion(dt);if(!e.dead&&!e.ranged&&dist2(e.x,e.y,p.x,p.y)<(e.radius+18)**2&&e.attackCooldown<=0){e.attackCooldown=e.attackRate;this.damagePlayer(e.damage)}}this.compact(this.enemies,this.enemyPool)}
 updateProjectiles(dt){for(const q of this.projectiles){if(!q.active)continue;q.update(dt);if(q.friendly){for(const e of this.enemies){if(e.dead||q.hitIds.has(e)||dist2(q.x,q.y,e.x,e.y)>(q.radius+e.radius)**2)continue;q.hitIds.add(e);this.damageEnemy(e,q.damage,q.vx*.25,q.vy*.25);if(--q.pierce<0){q.active=false;break}}}else if(!this.player.dead&&dist2(q.x,q.y,this.player.x,this.player.y)<(q.radius+18)**2){q.active=false;this.damagePlayer(q.damage)}}this.compact(this.projectiles,this.projectilePool)}
 updateHazards(dt){for(const h of this.hazards){if(!h.active)continue;h.update(dt);if(h.type==='mine'&&!h.detonated&&h.age>=h.warmup){h.detonated=true;this.damageCircle(h.x,h.y,h.radius,h.damage,260,true,.2);this.visuals.ring({x:h.x,y:h.y,radius:h.radius,width:16,color:h.color});this.particles.burst(h.x,h.y,{count:24,important:true})}else if(h.type!=='mine'&&h.age>=h.warmup&&h.tick<=0){h.tick=.5;if(Math.hypot(this.player.x-h.x,this.player.y-h.y)<h.radius+18)this.damagePlayer(h.damage)}}this.compact(this.hazards,this.hazardPool)}
 updatePickups(dt){for(const x of this.pickups){if(!x.active)continue;if(x.update(dt,this.player,this.magnetForce>0)){x.active=false;if(x.type==='xp'){const n=this.player.addXp(x.value);if(n){this.pendingLevels+=n;this.runStats.levels+=n;this.openLevelUp()}}else if(x.type==='coin'){this.player.runCoins+=x.value;this.runStats.runCoins+=x.value}else if(x.type==='food')this.player.heal(this.player.maxHp*.22);else if(x.type==='shard')this.store.data.shards+=x.value;this.audio.pickup()}}this.compact(this.pickups,this.pickupPool)}
 openLevelUp(){if(this.awaitingChoice||this.pendingLevels<=0)return;this.awaitingChoice=true;this.paused=true;this.selectedChoices=this.generateChoices();this.audio.levelUp();this.cb.onLevelUp?.({choices:this.selectedChoices,rerolls:this.player.rerolls,level:this.player.level})}
 generateChoices(){const out=[],weaponSlots=this.player.weapons.size<4;for(const w of this.player.weapons.values()){const d=WEAPONS[w.id],pass=this.player.passives.get(d.evolveWith)||0;if(w.level>=d.maxLevel&&!w.evolved&&pass>=3)out.push({type:'evolve',id:w.id,title:d.evolvedName,desc:d.desc,icon:d.icon,rarity:'rare'});else if(w.level<d.maxLevel)out.push({type:'weapon',id:w.id,title:d.name,desc:d.levels[w.level-1]||d.desc,icon:d.icon,rarity:'normal'})}if(weaponSlots)for(const d of Object.values(WEAPONS))if(!this.player.weapons.has(d.id))out.push({type:'weapon-new',id:d.id,title:d.name,desc:d.desc,icon:d.icon,rarity:'normal'});for(const d of Object.values(PASSIVES)){const lv=this.player.passives.get(d.id)||0;if(lv<d.maxLevel)out.push({type:'passive',id:d.id,title:d.name,desc:d.desc,icon:d.icon,rarity:'normal'})}out.push({type:'heal',id:'heal',title:'补给',desc:'回复生命',icon:'✚',rarity:'normal'});out.sort(()=>Math.random()-.5);return out.slice(0,3)}
 rerollChoices(){if(!this.awaitingChoice||this.player.rerolls<=0)return null;this.player.rerolls--;this.selectedChoices=this.generateChoices();return{choices:this.selectedChoices,rerolls:this.player.rerolls,level:this.player.level}}
 chooseUpgrade(c){if(!this.awaitingChoice||!c)return false;if(c.type==='weapon-new')this.player.addWeapon(c.id,1);else if(c.type==='weapon')this.player.weapons.get(c.id).level++;else if(c.type==='evolve')this.player.weapons.get(c.id).evolved=true;else if(c.type==='passive')this.player.addPassive(c.id,(this.player.passives.get(c.id)||0)+1);else this.player.heal(this.player.maxHp*.35);this.pendingLevels--;this.cb.onWeapons?.(this.player);if(this.pendingLevels>0){this.selectedChoices=this.generateChoices();this.cb.onLevelUp?.({choices:this.selectedChoices,rerolls:this.player.rerolls,level:this.player.level})}else{this.awaitingChoice=false;this.paused=false;this.cb.onLevelUpClosed?.()}return true}
 updateSpawner(dt){if(this.mode!=='endless'&&!this.bossSpawned){this.remaining=Math.max(0,this.day.duration-this.elapsed);if(this.remaining<=0)this.spawnBoss()}const cap=this.enemyCap(),target=Math.min(cap,Math.round(16+Math.min(1,this.elapsed/(this.day.duration||600))*(cap-16)));this.spawnTimer-=dt;if(this.live()<target&&this.spawnTimer<=0){this.spawnEnemy();this.spawnTimer=.3}}
 update(dt){if(!this.running||this.paused||this.awaitingChoice)return;this.frame++;this.elapsed+=dt;this.runStats.survival=this.elapsed;this.magnetForce=Math.max(0,this.magnetForce-dt);this.player.update(dt,this.cb.getMovement?.()||{x:0,y:0});if(this.manualHeld&&this.player.cooldowns.manual<=0)this.manualSlash();this.updateSpawner(dt);this.updateEnemies(dt);this.updateWeapons(dt);this.updateProjectiles(dt);this.updateHazards(dt);this.updatePickups(dt);this.particles.update(dt);this.visuals.update(dt);if(this.settings.particleQuality!=='off'&&this.frame%5===0)this.particles.aura(this.player.x,this.player.y,this.hero.color);const f=1-Math.pow(.001,dt);this.camera.x+=(this.player.x-this.camera.x)*f;this.camera.y+=(this.player.y-this.camera.y)*f;if(this.boss&&this.boss.dead&&this.boss.deathAge>.48)this.finish(true,false);this.hudTimer-=dt;if(this.hudTimer<=0){this.updateHud();this.hudTimer=.1}}
 compact(a,p){let w=0;for(const x of a)if(x.active)a[w++]=x;else p.put(x);a.length=w}
 updateHud(force=false){if(!this.running&&!force)return;const p=this.player;this.cb.onHud?.({title:this.day.title,dayId:this.day.sourceDayId||this.day.bossId||this.day.id,mode:this.mode,timer:this.mode==='endless'?this.elapsed:this.remaining,hp:p.hp,maxHp:p.maxHp,xp:p.xp,nextXp:p.nextXp,level:p.level,kills:this.runStats.kills||0,runCoins:p.runCoins,enemies:this.live(),enemyCap:this.enemyCap(),boss:this.boss&&!this.boss.dead?{id:this.boss.bossId,name:this.boss.name,hp:this.boss.hp,maxHp:this.boss.maxHp,phase:this.boss.phase}:null,cooldowns:p.cooldowns,ultimateEnergy:p.ultimateEnergy})}
 finish(won,abandoned=false){if(!this.running)return;this.running=false;this.paused=true;const survival=Math.round(this.elapsed),coins=Math.max(0,Math.round((this.runStats.kills*.7+survival*.16+(won?this.day.rewardCoins:0))*(1+(this.store.data.meta.greed||0)*.04))+this.player.runCoins),shards=won&&this.mode!=='endless'?this.day.rewardShards:Math.floor(survival/240),s=this.store.data;s.coins+=coins;s.shards+=shards;s.totals.runs++;s.totals.kills+=this.runStats.kills;s.totals.coinsEarned+=coins;s.totals.shardsEarned+=shards;s.totals.bestSurvival=Math.max(s.totals.bestSurvival,survival);if(won){s.totals.wins++;s.totals.bossesKilled+=this.runStats.bosses;if(this.mode==='campaign')this.store.unlockAfterClear(this.day.id);if(this.mode==='daily'){s.daily.dailyModeDate=new Date().toISOString().slice(0,10);s.daily.dailyModeCleared=true}}this.store.save();const achievements=this.store.evaluateAchievements();won?this.audio.victory():!abandoned&&this.audio.defeat();this.cb.onRunEnd?.({won,abandoned,day:this.day,mode:this.mode,stats:{...this.runStats,survival,level:this.player.level},rewards:{coins,shards},achievements})}
 vibrate(a=4){if(!this.settings.vibration)return false;try{return navigator.vibrate?.(a>=9?[18,12,20]:a>=5?13:7)}catch{return false}}
 drawOrbit(ctx,now){const w=this.player.weapons.get('orbit');if(!w)return;const n=1+Math.floor((w.level+1)/2),r=74+w.level*8;for(let i=0;i<n;i++){const a=w.phase*1.75+i/n*TAU,p=this.project(this.player.x+Math.cos(a)*r,this.player.y+Math.sin(a)*r/ISO_Y,18);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(a+now*.004);ctx.globalCompositeOperation='lighter';ctx.strokeStyle='#83f4ff';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-12,0);ctx.quadraticCurveTo(0,-9,12,0);ctx.quadraticCurveTo(0,9,-12,0);ctx.stroke();ctx.restore()}}
 render(){const c=this.ctx,s=this.visuals.shake;this.shakeX=s?(Math.random()*2-1)*s:0;this.shakeY=s?(Math.random()*2-1)*s:0;c.setTransform(this.dpr,0,0,this.dpr,0,0);this.ground.draw(c,this.width,this.height,this.camera,this.day.map);const project=(x,y,z)=>this.project(x,y,z),now=performance.now();this.visuals.drawWorld(c,project,this.settings.particleQuality!=='off');for(const h of this.hazards)drawHazard(c,h,project);for(const p of this.pickups)drawPickup(c,p,project,now);const list=this.enemies.filter(e=>e.active).map(e=>({y:e.y,e}));list.push({y:this.player.y,p:true});list.sort((a,b)=>a.y-b.y);for(const x of list)x.p?drawPlayer(c,this.player,project,now,this.hero.color):drawEnemy(c,x.e,project);this.drawOrbit(c,now);for(const q of this.projectiles)drawProjectile(c,q,project);this.particles.draw(c,project,now,{width:this.width,height:this.height});this.visuals.drawText(c,project)}
 loop(now){const ms=Math.min(80,Math.max(0,now-this.last));this.last=now;this.frameEma=this.frameEma*.92+ms*.08;const target=this.settings.batterySaver?33.3:16.7;if(now-this.lastRender>=target-1){this.lastRender=now;if(this.running&&!this.paused&&!this.awaitingChoice){this.acc=Math.min(.1,this.acc+ms/1000);let n=0;while(this.acc>=1/60&&n++<4){this.update(1/60);this.acc-=1/60}}this.render()}requestAnimationFrame(x=>this.loop(x))}
 debugState(){return{running:this.running,paused:this.paused,mode:this.mode,day:this.day.id,elapsed:+this.elapsed.toFixed(2),enemies:this.live(),enemyCap:this.enemyCap(),level:this.player.level,hp:this.player.hp,weapons:[...this.player.weapons.values()]}}
 debugStress(n=100){while(this.live()<Math.min(n,this.enemyCap()))this.spawnEnemy();return this.debugState()}
 debugLevelUp(){this.pendingLevels++;this.openLevelUp();return this.selectedChoices}
}
