export const LANGUAGES=[
  {id:'zh-CN',label:'简体中文'},{id:'zh-TW',label:'繁體中文'},{id:'en',label:'English'},
  {id:'ja',label:'日本語'},{id:'ko',label:'한국어'},{id:'es',label:'Español'}
];
const zh={
'app.title':'霜刃幸存者：七夜远征','app.subtitle':'七夜远征 · 2.5D 割草生存','app.canvas':'霜刃幸存者游戏画面',
'orientation.title':'请横屏游玩','orientation.desc':'旋转设备后会自动切换回游戏。也可以尝试进入全屏并锁定横屏。','orientation.enter':'进入横屏','orientation.waiting':'等待设备旋转','orientation.requesting':'正在请求全屏横屏…','orientation.rotate':'请将设备旋转为横屏','orientation.manual':'浏览器不允许自动旋转，请手动横屏',
'menu.aria':'主菜单','menu.tabsAria':'主页切换','menu.tab.campaign':'远征','menu.tab.profile':'英雄','menu.tab.meta':'营地','menu.tab.records':'记录','wallet.coins':'远征金币','wallet.shards':'霜晶','settings.open':'打开设置',
'campaign.title':'七夜远征','campaign.desc':'逐夜推进，没有强制时间锁。','campaign.daily':'每日试炼','campaign.dailyDesc':'今日随机词缀 · 独立奖励','campaign.endless':'无尽冰原','campaign.endlessLocked':'通关第七夜后解锁',
'heroes.title':'远征者','heroes.desc':'不同英雄拥有不同初始武器。','daily.title':'今日补给','daily.refresh':'每日刷新','daily.claim':'领取','daily.claimed':'已领取','meta.title':'营地天赋','meta.desc':'永久强化，成本逐级增长。','records.title':'远征记录','records.desc':'成就与累计数据。','controls.footer':'WASD / 方向键移动 · J 斩击 · K 冲刺 · L 觉醒 · U 召回',
'game.aria':'游戏界面','game.firstNight':'第一夜','game.level':'等级 {value}','game.kills':'击破','game.coins':'金币','game.enemies':'敌人 {current}/{max}','game.pause':'暂停','game.bossPhase':'阶段 {value}','game.joystick':'移动摇杆','game.skills':'主动技能','skills.manual':'斩','skills.dash':'突','skills.ultimate':'觉','skills.magnet':'召',
'levelup.label':'等级提升','levelup.title':'等级 {level} · 选择一项强化','levelup.rerolls':'重抽次数 {value}','levelup.reroll':'重抽','choice.evolve':'武器进化','choice.weapon':'武器','choice.passive':'被动','choice.supply':'补给','choice.healName':'战地补给','choice.healDesc':'立即回复 35% 最大生命。',
'pause.title':'远征暂停','pause.desc':'怪物终于也获得了法定休息时间。','pause.resume':'继续战斗','pause.settings':'设置','pause.quit':'结束本局',
'result.complete':'远征完成','result.abandoned':'主动撤离','result.failed':'远征失败','result.return':'返回营地','result.winSubtitle':'{boss} 已被击败。','result.abandonSubtitle':'保留所得，结束本局。','result.failSubtitle':'成长仍会保留，下一局继续。','result.kills':'击破','result.level':'等级','result.survival':'存活','result.damage':'承伤','result.coins':'金币','result.shards':'霜晶','result.newAchievements':' · 新成就 {value}',
'settings.title':'游戏设置','settings.desc':'按设备性能调整反馈。','settings.language':'语言','settings.languageDesc':'切换后立即生效并自动保存。','settings.bgm':'背景音乐','settings.bgmDesc':'程序化循环配乐','settings.sfx':'攻击音效','settings.sfxDesc':'挥砍、命中与首领','settings.quality':'粒子质量','settings.qualityDesc':'高级保留完整效果。','settings.off':'关','settings.medium':'中等','settings.high':'高级','settings.shake':'界面抖动','settings.shakeDesc':'关闭可减少晃动。','settings.vibration':'设备震动','settings.vibrationDesc':'仅支持的设备生效。','settings.damage':'伤害数字','settings.damageDesc':'关闭可减少密集波次绘制。','settings.battery':'省电模式','settings.batteryDesc':'限制 30 FPS 并降低特效。','settings.reset':'重置存档','settings.saveVersion':'存档版本 {value}',
'dynamic.streak':'连续 {value} 天','dynamic.day':'第 {value} 夜','dynamic.cleared':'✓ 已通关 · 最佳 {value} 击破','dynamic.boss':'首领：{value}','dynamic.endlessOpen':'无限成长 · 威胁持续提高','dynamic.unlockDay':'通关第 {value} 夜解锁','dynamic.dailyDone':'今日已完成 · 可重复挑战','dynamic.dailyReady':'今日随机词缀 · 首次奖励','dynamic.contractClaimed':'已领取','dynamic.maxed':'已满','dynamic.totalKills':'累计击破','dynamic.wins':'远征胜利','dynamic.bestSurvival':'最长存活','dynamic.bossArrived':'{value} 已降临','dynamic.ultimateHits':'觉醒爆发 · 命中 {value}','dynamic.claimedSupply':'领取第 {streak} 天补给：{amount} 金币','dynamic.supplyAlready':'今日补给已经领取','dynamic.resetConfirm':'确定重置全部远征进度？','dynamic.resetDone':'存档已重置','dynamic.weaponEvolved':'{name} 完成进化。','dynamic.levelName':'{name} Lv.{level}','modes.daily':'每日试炼','modes.endless':'无尽冰原'
};
const en={...zh,
'app.title':'Frostblade Survivors: Seven-Night Expedition','app.subtitle':'Seven-Night Expedition · 2.5D survivor action','orientation.title':'Play in landscape','orientation.desc':'Rotate your device to return to the game.','orientation.enter':'Enter landscape','orientation.waiting':'Waiting for rotation','orientation.requesting':'Requesting landscape…','orientation.rotate':'Rotate your device','orientation.manual':'Please rotate manually',
'menu.tab.campaign':'Expedition','menu.tab.profile':'Heroes','menu.tab.meta':'Camp','menu.tab.records':'Records','campaign.title':'Seven-Night Expedition','campaign.desc':'Advance one night at a time.','campaign.daily':'Daily Trial','campaign.dailyDesc':'Random modifiers · Separate rewards','campaign.endless':'Endless Frostfield','campaign.endlessLocked':'Clear Night 7 to unlock','heroes.title':'Heroes','heroes.desc':'Each hero starts with a different weapon.','daily.title':'Daily Supply','daily.refresh':'Refreshes daily','daily.claim':'Claim','daily.claimed':'Claimed','meta.title':'Camp Talents','meta.desc':'Permanent upgrades with rising costs.','records.title':'Records','records.desc':'Achievements and lifetime statistics.','controls.footer':'WASD / Arrows move · J slash · K dash · L awaken · U recall',
'game.level':'Level {value}','game.kills':'Kills','game.coins':'Coins','game.enemies':'Enemies {current}/{max}','game.bossPhase':'Phase {value}','skills.manual':'ATK','skills.dash':'DASH','skills.ultimate':'ULT','skills.magnet':'PULL','levelup.label':'LEVEL UP','levelup.title':'Level {level} · Choose an upgrade','levelup.rerolls':'Rerolls {value}','levelup.reroll':'Reroll','choice.evolve':'Evolution','choice.weapon':'Weapon','choice.passive':'Passive','choice.supply':'Supply','choice.healName':'Field Supply','choice.healDesc':'Restore 35% maximum health.',
'pause.title':'Paused','pause.desc':'The monsters finally received a break.','pause.resume':'Resume','pause.settings':'Settings','pause.quit':'End Run','result.complete':'Expedition Complete','result.abandoned':'Retreated','result.failed':'Expedition Failed','result.return':'Return to Camp','result.winSubtitle':'{boss} was defeated.','result.abandonSubtitle':'Keep your gains and end the run.','result.failSubtitle':'Permanent growth remains. Try again.','result.kills':'Kills','result.level':'Level','result.survival':'Survival','result.damage':'Damage taken','result.coins':'Coins','result.shards':'Shards','result.newAchievements':' · {value} new achievement(s)',
'settings.title':'Settings','settings.desc':'Tune feedback for your device.','settings.language':'Language','settings.languageDesc':'Applies immediately and saves automatically.','settings.bgm':'Music','settings.bgmDesc':'Procedural looping soundtrack','settings.sfx':'Combat SFX','settings.sfxDesc':'Slashes, hits, and bosses','settings.quality':'Particle Quality','settings.qualityDesc':'High keeps the full effect style.','settings.off':'Off','settings.medium':'Medium','settings.high':'High','settings.shake':'Screen Shake','settings.shakeDesc':'Disable to reduce motion.','settings.vibration':'Vibration','settings.vibrationDesc':'Supported devices only.','settings.damage':'Damage Numbers','settings.damageDesc':'Disable to reduce dense-wave drawing.','settings.battery':'Battery Saver','settings.batteryDesc':'Caps at 30 FPS and lowers effects.','settings.reset':'Reset Save','settings.saveVersion':'Save version {value}',
'dynamic.streak':'{value}-day streak','dynamic.day':'Night {value}','dynamic.cleared':'✓ Cleared · Best {value} kills','dynamic.boss':'Boss: {value}','dynamic.endlessOpen':'Infinite growth · Rising threat','dynamic.unlockDay':'Clear Night {value} to unlock','dynamic.dailyDone':'Completed today · Replay available','dynamic.dailyReady':'Random modifiers · First-clear reward','dynamic.contractClaimed':'Claimed','dynamic.maxed':'MAX','dynamic.totalKills':'Total kills','dynamic.wins':'Wins','dynamic.bestSurvival':'Best survival','dynamic.bossArrived':'{value} has arrived','dynamic.ultimateHits':'Awakening burst · {value} hits','dynamic.claimedSupply':'Day {streak} supply: {amount} coins','dynamic.supplyAlready':'Today’s supply is already claimed','dynamic.resetConfirm':'Reset all expedition progress?','dynamic.resetDone':'Save reset','dynamic.weaponEvolved':'{name} evolved.','dynamic.levelName':'{name} Lv.{level}','modes.daily':'Daily Trial','modes.endless':'Endless Frostfield'
};
const ja={...en,'app.title':'フロストブレード・サバイバー：七夜遠征','menu.tab.campaign':'遠征','menu.tab.profile':'英雄','menu.tab.meta':'拠点','menu.tab.records':'記録','campaign.title':'七夜遠征','campaign.daily':'デイリー試練','campaign.endless':'無限氷原','settings.title':'ゲーム設定','settings.language':'言語','settings.bgm':'BGM','settings.sfx':'戦闘SE','settings.quality':'パーティクル品質','settings.off':'オフ','settings.medium':'中','settings.high':'高','settings.shake':'画面揺れ','settings.vibration':'端末振動','settings.damage':'ダメージ表示','settings.battery':'省電力モード','levelup.label':'レベルアップ','levelup.reroll':'再抽選','pause.resume':'戦闘を再開','result.return':'拠点へ戻る'};
const ko={...en,'app.title':'프로스트블레이드 서바이버: 일곱 밤 원정','menu.tab.campaign':'원정','menu.tab.profile':'영웅','menu.tab.meta':'야영지','menu.tab.records':'기록','campaign.title':'일곱 밤 원정','campaign.daily':'일일 시련','campaign.endless':'무한 설원','settings.title':'게임 설정','settings.language':'언어','settings.bgm':'배경 음악','settings.sfx':'전투 효과음','settings.quality':'파티클 품질','settings.off':'끔','settings.medium':'중간','settings.high':'높음','settings.shake':'화면 흔들림','settings.vibration':'기기 진동','settings.damage':'피해 숫자','settings.battery':'절전 모드','levelup.label':'레벨 업','levelup.reroll':'재추첨','pause.resume':'전투 계속','result.return':'야영지로'};
const es={...en,'app.title':'Supervivientes de Frostblade: Expedición de Siete Noches','menu.tab.campaign':'Expedición','menu.tab.profile':'Héroes','menu.tab.meta':'Campamento','menu.tab.records':'Récords','campaign.title':'Expedición de Siete Noches','campaign.daily':'Prueba diaria','campaign.endless':'Tundra infinita','settings.title':'Ajustes','settings.language':'Idioma','settings.bgm':'Música','settings.sfx':'Efectos','settings.quality':'Partículas','settings.off':'No','settings.medium':'Media','settings.high':'Alta','settings.shake':'Sacudida','settings.vibration':'Vibración','settings.damage':'Números de daño','settings.battery':'Ahorro de batería','levelup.label':'SUBIDA DE NIVEL','levelup.reroll':'Repetir','pause.resume':'Continuar','result.return':'Volver al campamento'};
const tw=Object.fromEntries(Object.entries(zh).map(([k,v])=>[k,String(v).replaceAll('远征','遠征').replaceAll('设置','設定').replaceAll('伤害','傷害').replaceAll('敌人','敵人').replaceAll('击破','擊破').replaceAll('金币','金幣').replaceAll('领取','領取').replaceAll('升级','升級').replaceAll('选择','選擇').replaceAll('关闭','關閉').replaceAll('记录','紀錄').replaceAll('强化','強化').replaceAll('移动','移動').replaceAll('横屏','橫屏').replaceAll('浏览器','瀏覽器').replaceAll('进化','進化').replaceAll('范围','範圍')]));
const UI={'zh-CN':zh,'zh-TW':tw,en,ja,ko,es};
const DATA_EN={
 days:{1:{title:'Frostfield Trial',subtitle:'Learn to move while surrounded'},2:{title:'Gale Rift',subtitle:'Speed becomes a second layer of armor'},3:{title:'Corrupted Grove',subtitle:'Do not contemplate life in poison'},4:{title:'Thunder Mine',subtitle:'Ranged barrages demand attention'},5:{title:'Mirror Lake Hunt',subtitle:'Elite enemies finally got a budget'},6:{title:'Ruins of the Royal City',subtitle:'All enemy types enter together'},7:{title:'Throne of the Final Night',subtitle:'Defeat the Lord of the Cold Night'}},
 heroes:{bladeguard:{name:'Frostblade Guard',desc:'Balanced melee hero with Frost Slash.'},stormhunter:{name:'Storm Hunter',desc:'Fast hero with Chain Lightning.'},runekeeper:{name:'Rune Keeper',desc:'Area-control hero with Rune Mine.'}},
 weapons:{blade:{name:'Frost Slash',evolvedName:'Eclipse Frostblade',desc:'Automatically slashes the nearest enemy.'},orbit:{name:'Ice Wheel Guard',evolvedName:'Blizzard Crown',desc:'Orbiting ice blades deal continuous damage.'},lightning:{name:'Chain Lightning',evolvedName:'Sky Tempest',desc:'Lightning jumps between enemies.'},chakram:{name:'Returning Moonblade',evolvedName:'Twin-Moon Corridor',desc:'Throws a returning blade.'},mine:{name:'Rune Mine',evolvedName:'Starfall Array',desc:'Places a delayed explosive rune.'},nova:{name:'Sacred Frost Nova',evolvedName:'Everfrost Sanctuary',desc:'Releases a slowing ring shockwave.'}},
 passives:{might:{name:'Might',desc:'All damage +10%.'},haste:{name:'Haste',desc:'Weapon cooldown -7%.'},vitality:{name:'Vitality',desc:'Maximum health +12%.'},area:{name:'Domain',desc:'Attack area +9%.'},armor:{name:'Armor',desc:'Damage taken -1.5.'},magnet:{name:'Gravity',desc:'Pickup range +16%.'},speed:{name:'Fleetfoot',desc:'Movement speed +7%.'},luck:{name:'Fortune',desc:'Improves rare upgrades.'}},
 meta:{power:{name:'Sharpen',desc:'Permanent damage +3%/rank'},health:{name:'Fortify',desc:'Permanent health +4%/rank'},haste:{name:'Tactics',desc:'Permanent cooldown -1.5%/rank'},magnet:{name:'Scavenging',desc:'Permanent pickup range +5%/rank'},greed:{name:'Logistics',desc:'Run rewards +4%/rank'},reroll:{name:'Contingency',desc:'Rerolls per run +1'}},
 bosses:{1:{name:'Frostfang Chieftain'},2:{name:'Gale Hunter'},3:{name:'Spore Matriarch'},4:{name:'Thunderforge Overseer'},5:{name:'Mirror Lake Twins'},6:{name:'Crownless Knight'},7:{name:'Lord of the Cold Night'}},
 achievements:{firstBlood:{name:'First Blood',desc:'Defeat 1 enemy'},thousand:{name:'Army Breaker',desc:'Defeat 1,000 enemies'},veteran:{name:'Veteran of Seven Nights',desc:'Clear Night 7'},collector:{name:'Shard Collector',desc:'Earn 40 shards'},survivor:{name:'Refuse to Fall',desc:'Survive 8 minutes'}},
 contracts:{kills:{name:'Clear the Field'},levels:{name:'Rapid Growth'},survive:{name:'Hold the Line'},coins:{name:'Battlefield Scavenger'},boss:{name:'Boss Hunter'}}
};
let locale='zh-CN';
export const normalizeLocale=v=>LANGUAGES.some(x=>x.id===v)?v:'zh-CN';
export function setLocale(v){locale=normalizeLocale(v);document.documentElement.lang=locale;document.documentElement.dataset.lang=locale;return locale}
export const getLocale=()=>locale;
const fmt=(s,p={})=>String(s).replace(/\{(\w+)\}/g,(_,k)=>p[k]??`{${k}}`);
export const t=(key,p={})=>fmt(UI[locale]?.[key]??en[key]??zh[key]??key,p);
export function dataText(group,id,field,fallback=''){if(locale.startsWith('zh'))return fallback;return DATA_EN[group]?.[id]?.[field]??fallback}
export function dataList(group,id,field,fallback=[]){return fallback}
export function formatNumber(v){try{return new Intl.NumberFormat(locale).format(v)}catch{return String(v)}}
export function applyStaticTranslations(root=document){root.querySelectorAll('[data-i18n]').forEach(n=>n.textContent=t(n.dataset.i18n));root.querySelectorAll('[data-i18n-title]').forEach(n=>n.title=t(n.dataset.i18nTitle));root.querySelectorAll('[data-i18n-aria]').forEach(n=>n.setAttribute('aria-label',t(n.dataset.i18nAria)));document.title=`${t('app.title')} · v1.3.1`}
