import {ACHIEVEMENTS,DAILY_REWARDS,HEROES,META_UPGRADES,STORAGE_KEY,VERSION} from './config.js';
const todayKey=()=>new Date().toISOString().slice(0,10);
const yesterdayKey=()=>{const d=new Date();d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)};
export function createDefaultSave(){return{version:1,gameVersion:VERSION,coins:0,shards:0,unlockedDay:1,clearedDays:[],selectedHero:'bladeguard',unlockedHeroes:['bladeguard'],meta:Object.fromEntries(Object.keys(META_UPGRADES).map(id=>[id,0])),achievements:{},best:{},totals:{kills:0,runs:0,wins:0,coinsEarned:0,shardsEarned:0,bestSurvival:0,clearedDays:0,levelsGained:0,bossesKilled:0},daily:{lastClaim:'',streak:0,contractDate:'',contractProgress:{},contractClaimed:{},dailyModeDate:'',dailyModeCleared:false},settings:{language:'zh-CN',bgm:.42,sfx:.7,particleQuality:'medium',screenShake:true,vibration:true,damageNumbers:true,batterySaver:false}}}
function merge(target,source){if(!source||typeof source!=='object')return target;for(const [k,v] of Object.entries(source)){if(Array.isArray(v))target[k]=[...v];else if(v&&typeof v==='object')target[k]=merge(target[k]&&typeof target[k]==='object'?target[k]:{},v);else target[k]=v}return target}
function sanitize(s){s.coins=Math.max(0,Math.floor(+s.coins||0));s.shards=Math.max(0,Math.floor(+s.shards||0));s.unlockedDay=Math.max(1,Math.min(7,Math.floor(+s.unlockedDay||1)));s.clearedDays=[...new Set((s.clearedDays||[]).map(Number).filter(v=>v>=1&&v<=7))];s.unlockedHeroes=[...new Set((s.unlockedHeroes||[]).filter(id=>HEROES[id]))];if(!s.unlockedHeroes.includes('bladeguard'))s.unlockedHeroes.unshift('bladeguard');if(!s.unlockedHeroes.includes(s.selectedHero))s.selectedHero='bladeguard';for(const [id,d] of Object.entries(META_UPGRADES))s.meta[id]=Math.max(0,Math.min(d.maxLevel,Math.floor(+s.meta[id]||0)));if(!['zh-CN','zh-TW','en','ja','ko','es'].includes(s.settings.language))s.settings.language='zh-CN';if(!['off','medium','high'].includes(s.settings.particleQuality))s.settings.particleQuality='medium';for(const k of ['screenShake','vibration','damageNumbers','batterySaver'])s.settings[k]=s.settings[k]!==false;s.settings.bgm=Math.max(0,Math.min(1,+s.settings.bgm||0));s.settings.sfx=Math.max(0,Math.min(1,+s.settings.sfx||0));s.totals.clearedDays=s.clearedDays.length;s.gameVersion=VERSION;return s}
export class SaveStore{constructor(){this.data=this.load();this.listeners=new Set()}load(){const d=createDefaultSave();try{const raw=localStorage.getItem(STORAGE_KEY);return sanitize(raw?merge(d,JSON.parse(raw)):d)}catch{return d}}save(){sanitize(this.data);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(this.data))}catch{}for(const fn of this.listeners)fn(this.data);return this.data}subscribe(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn)}reset(){this.data=createDefaultSave();this.save()}addCoins(v){v=Math.max(0,Math.floor(+v||0));this.data.coins+=v;this.data.totals.coinsEarned+=v;this.save()}spendCoins(v){v=Math.max(0,Math.floor(+v||0));if(this.data.coins<v)return false;this.data.coins-=v;this.save();return true}addShards(v){v=Math.max(0,Math.floor(+v||0));this.data.shards+=v;this.data.totals.shardsEarned+=v;this.save()}claimDaily(){const today=todayKey();if(this.data.daily.lastClaim===today)return{claimed:false,amount:0};this.data.daily.streak=this.data.daily.lastClaim===yesterdayKey()?Math.min(7,this.data.daily.streak+1):1;this.data.daily.lastClaim=today;const amount=DAILY_REWARDS[this.data.daily.streak-1];this.data.coins+=amount;this.data.totals.coinsEarned+=amount;this.save();return{claimed:true,amount,streak:this.data.daily.streak}}unlockAfterClear(id){id=+id;if(!this.data.clearedDays.includes(id))this.data.clearedDays.push(id);this.data.unlockedDay=Math.max(this.data.unlockedDay,Math.min(7,id+1));if(id>=3&&!this.data.unlockedHeroes.includes('stormhunter'))this.data.unlockedHeroes.push('stormhunter');if(id>=5&&!this.data.unlockedHeroes.includes('runekeeper'))this.data.unlockedHeroes.push('runekeeper');this.data.totals.clearedDays=this.data.clearedDays.length;this.save()}evaluateAchievements(){const unlocked=[];for(const d of Object.values(ACHIEVEMENTS)){if(this.data.achievements[d.id]||!d.test(this.data.totals))continue;this.data.achievements[d.id]=Date.now();this.data.coins+=180;this.data.totals.coinsEarned+=180;unlocked.push(d)}if(unlocked.length)this.save();return unlocked}}
export function makeDailySeed(date=todayKey()){let seed=2166136261;for(const c of date){seed^=c.charCodeAt(0);seed=Math.imul(seed,16777619)}return seed>>>0}
export function seededRandom(seed){let v=seed>>>0||1;return()=>{v^=v<<13;v^=v>>>17;v^=v<<5;return(v>>>0)/4294967296}}
export function getDailyContracts(save,date=todayKey()){if(save.daily.contractDate!==date){save.daily.contractDate=date;save.daily.contractProgress={};save.daily.contractClaimed={}}const r=seededRandom(makeDailySeed(date));const pool=[{id:'kills',name:'清理战场',metric:'kills',target:240+Math.floor(r()*180),reward:150},{id:'levels',name:'迅速成长',metric:'levels',target:12+Math.floor(r()*8),reward:130},{id:'survive',name:'坚守阵线',metric:'survival',target:300+Math.floor(r()*120),reward:180},{id:'coins',name:'战场拾荒',metric:'runCoins',target:90+Math.floor(r()*70),reward:140},{id:'boss',name:'首领猎手',metric:'bosses',target:1,reward:220}];const out=[];while(out.length<3&&pool.length)out.push(pool.splice(Math.floor(r()*pool.length),1)[0]);return out}
export {todayKey};
