import {ACHIEVEMENTS,DAYS,HEROES,META_UPGRADES,PASSIVES,WEAPONS,metaCost} from './config.js';
import {getDailyContracts,todayKey} from './storage.js';
import {LANGUAGES,applyStaticTranslations,dataList,dataText,formatNumber,setLocale,t} from './i18n.js';
const $=s=>document.querySelector(s);
const time=s=>{s=Math.max(0,Math.floor(s));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
export class UIController{
 constructor(store,audio){this.store=store;this.audio=audio;this.game=null;this.input=null;this.activeMenuTab='campaign';this.settingsOpenedFromPause=false;this.cache();this.bind();this.renderAll()}
 cache(){this.d={menu:$('#menuScreen'),game:$('#gameScreen'),tabs:[...document.querySelectorAll('#mobileMenuTabs [data-tab]')],panels:[...document.querySelectorAll('[data-menu-panel]')],coins:$('#coinText'),shards:$('#shardText'),streak:$('#streakBadge'),days:$('#dayList'),heroes:$('#heroList'),contracts:$('#contractList'),claim:$('#claimDailyButton'),dailyDate:$('#dailyDateText'),dailyMode:$('#dailyModeButton'),dailyDesc:$('#dailyModeDesc'),endless:$('#endlessModeButton'),meta:$('#metaUpgradeList'),records:$('#recordSummary'),achievements:$('#achievementList'),settings:$('#settingsOverlay'),openSettings:$('#openSettings'),closeSettings:$('#closeSettings'),pauseSettings:$('#pauseSettingsButton'),language:$('#languageSelect'),bgm:$('#bgmVolume'),sfx:$('#sfxVolume'),bgmValue:$('#bgmValue'),sfxValue:$('#sfxValue'),quality:$('#particleQuality'),shake:$('#screenShakeToggle'),vibration:$('#vibrationToggle'),damage:$('#damageNumberToggle'),battery:$('#batterySaverToggle'),reset:$('#resetSaveButton'),saveVersion:$('#saveVersionText'),pauseOverlay:$('#pauseOverlay'),pause:$('#pauseButton'),resume:$('#resumeButton'),quit:$('#quitRunButton'),levelOverlay:$('#levelUpOverlay'),levelTitle:$('#levelUpTitle'),choices:$('#levelChoiceList'),reroll:$('#rerollButton'),rerollText:$('#rerollText'),result:$('#runEndOverlay'),resultTitle:$('#resultTitle'),resultSubtitle:$('#resultSubtitle'),resultStats:$('#resultStats'),resultRewards:$('#resultRewards'),resultContinue:$('#resultContinueButton'),runTitle:$('#runTitle'),timer:$('#runTimer'),hpFill:$('#hpFill'),hpText:$('#hpText'),xpFill:$('#xpFill'),levelText:$('#levelText'),kills:$('#killText'),runCoins:$('#runCoinText'),enemy:$('#enemyText'),bossBar:$('#bossBar'),bossName:$('#bossName'),bossPhase:$('#bossPhase'),bossHp:$('#bossHpFill'),weaponStrip:$('#weaponStrip'),toast:$('#toast'),active:[...document.querySelectorAll('.active-skill')]}}
 attach(game,input){this.game=game;this.input=input}
 bind(){const d=this.d;d.openSettings.onclick=()=>this.openSettings(false);d.pauseSettings.onclick=()=>this.openSettings(true);d.closeSettings.onclick=()=>this.closeSettings();d.settings.onpointerdown=e=>{if(e.target===d.settings)this.closeSettings()};d.pause.onclick=()=>this.game?.setPaused(true);d.resume.onclick=()=>this.game?.setPaused(false);d.quit.onclick=()=>this.game?.quitRun();d.resultContinue.onclick=()=>this.returnToMenu();d.reroll.onclick=()=>{const r=this.game?.rerollChoices();if(r)this.showLevelUp(r)};d.claim.onclick=()=>{const r=this.store.claimDaily();this.showToast(r.claimed?t('dynamic.claimedSupply',{streak:r.streak,amount:formatNumber(r.amount)}):t('dynamic.supplyAlready'));this.renderAll()};d.dailyMode.onclick=()=>this.game?.startRun({mode:'daily'});d.endless.onclick=()=>{if(this.store.data.clearedDays.includes(7))this.game?.startRun({mode:'endless',dayId:7})};for(const b of d.tabs)b.onclick=()=>this.switchTab(b.dataset.tab);addEventListener('resize',()=>this.applyTab(),{passive:true});d.language.onchange=()=>{const l=setLocale(d.language.value);this.store.data.settings.language=l;this.store.save();this.renderAll();this.game?.updateHud(true);if(this.game?.player)this.onWeapons(this.game.player);if(this.game?.awaitingChoice)this.showLevelUp({choices:this.game.selectedChoices,rerolls:this.game.player.rerolls,level:this.game.player.level})};d.bgm.oninput=()=>{this.store.data.settings.bgm=+d.bgm.value;this.volumes();this.store.save();this.audio.applySettings();this.audio.ensure()};d.sfx.oninput=()=>{this.store.data.settings.sfx=+d.sfx.value;this.volumes();this.store.save();this.audio.applySettings();this.audio.ensure()};for(const b of d.quality.querySelectorAll('button'))b.onclick=()=>{this.store.data.settings.particleQuality=b.dataset.value;this.store.save();this.renderSettings();this.game?.resize()};this.toggle(d.shake,'screenShake');this.toggle(d.vibration,'vibration',v=>navigator.vibrate?.(v?8:0));this.toggle(d.damage,'damageNumbers');this.toggle(d.battery,'batterySaver',()=>this.game?.resize());d.reset.onclick=()=>{if(!confirm(t('dynamic.resetConfirm')))return;this.store.reset();setLocale(this.store.data.settings.language||'zh-CN');this.renderAll();this.showToast(t('dynamic.resetDone'))}}
 toggle(el,key,after){el.onchange=()=>{this.store.data.settings[key]=el.checked;this.store.save();after?.(el.checked)}}
 renderAll(){applyStaticTranslations();this.wallet();this.campaign();this.heroes();this.daily();this.meta();this.records();this.renderSettings();this.applyTab()}
 wallet(){this.d.coins.textContent=formatNumber(this.store.data.coins);this.d.shards.textContent=formatNumber(this.store.data.shards);this.d.streak.textContent=t('dynamic.streak',{value:Math.max(1,this.store.data.daily.streak||1)})}
 campaign(){const s=this.store.data;this.d.days.innerHTML=DAYS.map(day=>{const unlocked=day.id<=s.unlockedDay,cleared=s.clearedDays.includes(day.id),best=s.best[`campaign:${day.id}`];return`<button class="day-card ${unlocked?'':'locked'} ${cleared?'cleared':''}" data-day="${day.id}" ${unlocked?'':'disabled'}><span>${t('dynamic.day',{value:day.id})}</span><strong>${dataText('days',day.id,'title',day.title)}</strong><small>${dataText('days',day.id,'subtitle',day.subtitle)}</small><em>${cleared?t('dynamic.cleared',{value:best?.kills||0}):t('dynamic.boss',{value:dataText('bosses',day.id,'name',day.boss)})}</em>${unlocked?'':'<i class="lock">🔒</i>'}</button>`}).join('');for(const b of this.d.days.querySelectorAll('[data-day]'))b.onclick=()=>this.game?.startRun({mode:'campaign',dayId:+b.dataset.day});const open=s.clearedDays.includes(7);this.d.endless.disabled=!open;this.d.endless.querySelector('small').textContent=open?t('dynamic.endlessOpen'):t('campaign.endlessLocked');this.d.dailyDesc.textContent=s.daily.dailyModeDate===todayKey()&&s.daily.dailyModeCleared?t('dynamic.dailyDone'):t('dynamic.dailyReady')}
 heroes(){const s=this.store.data;this.d.heroes.innerHTML=Object.values(HEROES).map(h=>{const unlocked=s.unlockedHeroes.includes(h.id);return`<button class="hero-card ${s.selectedHero===h.id?'selected':''}" data-hero="${h.id}" ${unlocked?'':'disabled'}><div class="hero-avatar" style="color:${h.color}">${h.icon}</div><div><strong>${dataText('heroes',h.id,'name',h.name)}</strong><small>${unlocked?dataText('heroes',h.id,'desc',h.desc):t('dynamic.unlockDay',{value:h.unlockDay})}</small></div></button>`}).join('');for(const b of this.d.heroes.querySelectorAll('[data-hero]'))b.onclick=()=>{s.selectedHero=b.dataset.hero;this.store.save();this.heroes()}}
 getDailyContracts(){this.currentContracts=getDailyContracts(this.store.data);return this.currentContracts}
 daily(){const s=this.store.data,date=todayKey(),claimed=s.daily.lastClaim===date;this.d.claim.disabled=claimed;this.d.claim.textContent=claimed?t('daily.claimed'):t('daily.claim');this.d.dailyDate.textContent=`${date} · ${t('dynamic.streak',{value:s.daily.streak||0})}`;this.d.contracts.innerHTML=this.getDailyContracts().map(c=>{const p=Math.min(c.target,s.daily.contractProgress[c.id]||0),done=p>=c.target;return`<div class="contract"><div><span>${done?'✓ ':''}${dataText('contracts',c.id,'name',c.name)}</span><small>${Math.floor(p)} / ${c.target} · ${s.daily.contractClaimed[c.id]?t('dynamic.contractClaimed'):`+${c.reward}`}</small></div><div class="progress-track"><i style="width:${p/c.target*100}%"></i></div></div>`}).join('');this.store.save()}
 meta(){const s=this.store.data;this.d.meta.innerHTML=Object.values(META_UPGRADES).map(def=>{const lv=s.meta[def.id]||0,max=lv>=def.maxLevel,cost=max?0:metaCost(def,lv);return`<div class="meta-upgrade"><div class="meta-icon">${def.icon}</div><div><strong>${dataText('meta',def.id,'name',def.name)} ${lv}/${def.maxLevel}</strong><small>${dataText('meta',def.id,'desc',def.desc)}</small></div><button data-meta="${def.id}" ${max||s.coins<cost?'disabled':''}>${max?t('dynamic.maxed'):`${cost} 🪙`}</button></div>`}).join('');for(const b of this.d.meta.querySelectorAll('[data-meta]'))b.onclick=()=>{const id=b.dataset.meta,d=META_UPGRADES[id],lv=s.meta[id]||0,c=metaCost(d,lv);if(lv>=d.maxLevel||!this.store.spendCoins(c))return;s.meta[id]=lv+1;this.store.save();this.renderAll()}}
 records(){const x=this.store.data.totals;this.d.records.innerHTML=`<div><b>${formatNumber(x.kills)}</b><small>${t('dynamic.totalKills')}</small></div><div><b>${formatNumber(x.wins)}</b><small>${t('dynamic.wins')}</small></div><div><b>${time(x.bestSurvival)}</b><small>${t('dynamic.bestSurvival')}</small></div>`;this.d.achievements.innerHTML=Object.values(ACHIEVEMENTS).map(a=>`<div class="achievement ${this.store.data.achievements[a.id]?'done':''}"><span>${this.store.data.achievements[a.id]?'✦':'◇'} ${dataText('achievements',a.id,'name',a.name)}</span><span>${dataText('achievements',a.id,'desc',a.desc)}</span></div>`).join('')}
 renderSettings(){const s=this.store.data.settings;if(!this.d.language.options.length)this.d.language.innerHTML=LANGUAGES.map(l=>`<option value="${l.id}">${l.label}</option>`).join('');this.d.language.value=s.language||'zh-CN';this.d.bgm.value=s.bgm;this.d.sfx.value=s.sfx;this.d.shake.checked=s.screenShake;this.d.vibration.checked=s.vibration;this.d.damage.checked=s.damageNumbers;this.d.battery.checked=s.batterySaver;for(const b of this.d.quality.querySelectorAll('button'))b.classList.toggle('active',b.dataset.value===s.particleQuality);this.volumes();this.d.saveVersion.textContent=t('settings.saveVersion',{value:this.store.data.version})}
 volumes(){this.d.bgmValue.value=`${Math.round(this.d.bgm.value*100)}%`;this.d.sfxValue.value=`${Math.round(this.d.sfx.value*100)}%`}
 switchTab(tab){this.activeMenuTab=tab||'campaign';this.applyTab()}
 applyTab(){const coarse=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0,mobile=matchMedia('(max-width:720px)').matches||(coarse&&Math.min(innerWidth,innerHeight)<=720);for(const b of this.d.tabs)b.classList.toggle('active',b.dataset.tab===this.activeMenuTab);for(const p of this.d.panels){const active=p.dataset.menuPanel===this.activeMenuTab;p.classList.toggle('mobile-active',!mobile||active);p.hidden=mobile&&!active}}
 openSettings(fromPause){this.settingsOpenedFromPause=!!fromPause;if(this.game?.running&&!this.game.paused)this.game.setPaused(true);this.renderSettings();this.d.settings.hidden=false;this.audio.ensure()}
 closeSettings(){this.d.settings.hidden=true;if(this.settingsOpenedFromPause)this.d.pauseOverlay.hidden=false;this.settingsOpenedFromPause=false}
 onRunStart({day,mode}){this.d.menu.classList.remove('active');this.d.game.classList.add('active');this.d.result.hidden=this.d.pauseOverlay.hidden=this.d.levelOverlay.hidden=true;this.d.runTitle.textContent=mode==='daily'?t('modes.daily'):mode==='endless'?t('modes.endless'):dataText('days',day.sourceDayId||day.id,'title',day.title);this.input?.setEnabled(true)}
 onHud(s){this.d.runTitle.textContent=s.mode==='daily'?t('modes.daily'):s.mode==='endless'?t('modes.endless'):dataText('days',s.dayId,'title',s.title);this.d.timer.textContent=time(s.timer);this.d.hpFill.style.width=`${Math.max(0,s.hp/s.maxHp*100)}%`;this.d.hpText.textContent=`${Math.ceil(s.hp)} / ${s.maxHp}`;this.d.xpFill.style.width=`${Math.max(0,s.xp/s.nextXp*100)}%`;this.d.levelText.textContent=t('game.level',{value:s.level});this.d.kills.textContent=formatNumber(s.kills);this.d.runCoins.textContent=formatNumber(s.runCoins);this.d.enemy.textContent=t('game.enemies',{current:s.enemies,max:s.enemyCap});if(s.boss){this.d.bossBar.hidden=false;this.d.bossName.textContent=dataText('bosses',s.boss.id||s.dayId,'name',s.boss.name);this.d.bossPhase.textContent=t('game.bossPhase',{value:s.boss.phase});this.d.bossHp.style.width=`${Math.max(0,s.boss.hp/s.boss.maxHp*100)}%`}else this.d.bossBar.hidden=true;const max={manual:.42,dash:3.2,ultimate:100,magnet:18};for(const b of this.d.active){const a=b.dataset.active,v=a==='ultimate'?100-s.ultimateEnergy:s.cooldowns[a]||0;b.querySelector('i').style.height=`${Math.max(0,Math.min(100,v/max[a]*100))}%`}}
 onWeapons(p){this.d.weaponStrip.innerHTML=[...p.weapons.values()].map(w=>{const def=WEAPONS[w.id];return`<div class="weapon-badge" title="${dataText('weapons',w.id,w.evolved?'evolvedName':'name',w.evolved?def.evolvedName:def.name)}"><b>${def.icon}</b><span>${w.evolved?'E':w.level}</span></div>`}).join('')}
 showLevelUp(x){this.d.levelOverlay.hidden=false;this.d.levelTitle.textContent=t('levelup.title',{level:x.level});this.d.rerollText.textContent=t('levelup.rerolls',{value:x.rerolls});this.d.reroll.disabled=x.rerolls<=0;this.d.choices.innerHTML=x.choices.map((c,i)=>{let title=c.title,desc=c.desc,tag=c.type==='evolve'?t('choice.evolve'):c.type.includes('weapon')?t('choice.weapon'):c.type==='passive'?t('choice.passive'):t('choice.supply');if(c.type.includes('weapon')){const d=WEAPONS[c.id];title=dataText('weapons',c.id,c.type==='evolve'?'evolvedName':'name',title);desc=c.type==='weapon-new'?dataText('weapons',c.id,'desc',desc):desc}else if(c.type==='passive'){const d=PASSIVES[c.id];title=dataText('passives',c.id,'name',d?.name||title);desc=dataText('passives',c.id,'desc',desc)}else if(c.type==='heal'){title=t('choice.healName');desc=t('choice.healDesc')}return`<button class="level-card ${c.rarity==='normal'?'':'rare'}" data-choice="${i}"><div class="choice-icon">${c.icon}</div><h3>${title}</h3><p>${desc}</p><em>${tag}</em></button>`}).join('');for(const b of this.d.choices.querySelectorAll('[data-choice]'))b.onclick=()=>this.game?.chooseUpgrade(x.choices[+b.dataset.choice])}
 onLevelUpClosed(){this.d.levelOverlay.hidden=true}
 onPause(v){if(!this.game?.running)return;this.d.pauseOverlay.hidden=!v;this.input?.setEnabled(!v)}
 onRunEnd(r){this.input?.setEnabled(false);this.d.pauseOverlay.hidden=this.d.levelOverlay.hidden=true;this.d.result.hidden=false;this.d.resultTitle.textContent=r.won?t('result.complete'):r.abandoned?t('result.abandoned'):t('result.failed');const boss=dataText('bosses',r.day.sourceDayId||r.day.bossId||r.day.id,'name',r.day.boss);this.d.resultSubtitle.textContent=r.won?t('result.winSubtitle',{boss}):r.abandoned?t('result.abandonSubtitle'):t('result.failSubtitle');this.d.resultStats.innerHTML=`<div><b>${formatNumber(r.stats.kills)}</b><small>${t('result.kills')}</small></div><div><b>${r.stats.level}</b><small>${t('result.level')}</small></div><div><b>${time(r.stats.survival)}</b><small>${t('result.survival')}</small></div><div><b>${formatNumber(r.stats.damageTaken)}</b><small>${t('result.damage')}</small></div>`;this.d.resultRewards.innerHTML=`<div><b>+${formatNumber(r.rewards.coins)}</b><small>${t('result.coins')}</small></div><div><b>+${formatNumber(r.rewards.shards)}</b><small>${t('result.shards')}</small></div>`}
 returnToMenu(){this.d.result.hidden=true;this.d.game.classList.remove('active');this.d.menu.classList.add('active');this.renderAll()}
 showToast(m){this.d.toast.textContent=m;this.d.toast.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>this.d.toast.classList.remove('show'),1500)}
}
